import type { Provider, Notification, Message, User } from '../types';

export const mockProviders: Provider[] = [
  {
    id: '1',
    name: 'Pharmacie Centrale',
    type: 'pharmacy',
    description: 'Pharmacie moderne avec large gamme de médicaments et conseils personnalisés.',
    address: '123 Avenue de l\'Indépendance, Libreville',
    distance: 0.5,
    rating: 4.5,
    reviewCount: 124,
    tags: ['24h/24', 'Livraison', 'Conseil'],
    hours: {
      monday: { open: '08:00', close: '20:00' },
      tuesday: { open: '08:00', close: '20:00' },
      wednesday: { open: '08:00', close: '20:00' },
      thursday: { open: '08:00', close: '20:00' },
      friday: { open: '08:00', close: '20:00' },
      saturday: { open: '09:00', close: '18:00' },
      sunday: { open: '10:00', close: '16:00' },
    },
    services: ['Médicaments', 'Parapharmacie', 'Conseil pharmaceutique', 'Livraison'],
    isOpen: true,
  },
  {
    id: '2',
    name: 'Dr. Marie Moussavou',
    type: 'doctor',
    description: 'Médecin généraliste avec plus de 15 ans d\'expérience.',
    address: '45 Rue de la Paix, Libreville',
    distance: 1.2,
    rating: 4.8,
    reviewCount: 89,
    tags: ['Généraliste', 'Urgences', 'Consultation'],
    hours: {
      monday: { open: '09:00', close: '17:00' },
      tuesday: { open: '09:00', close: '17:00' },
      wednesday: { open: '09:00', close: '17:00' },
      thursday: { open: '09:00', close: '17:00' },
      friday: { open: '09:00', close: '17:00' },
      saturday: { open: '09:00', close: '12:00' },
      sunday: null,
    },
    services: ['Consultation générale', 'Vaccination', 'Certificats médicaux'],
    isOpen: true,
  },
  {
    id: '3',
    name: 'Clinique de la Sablière',
    type: 'clinic',
    description: 'Clinique moderne avec équipements de pointe et équipe médicale qualifiée.',
    address: '78 Boulevard Triomphal, Libreville',
    distance: 2.1,
    rating: 4.3,
    reviewCount: 156,
    tags: ['Spécialisée', 'Équipements', 'Urgences'],
    hours: {
      monday: { open: '07:00', close: '19:00' },
      tuesday: { open: '07:00', close: '19:00' },
      wednesday: { open: '07:00', close: '19:00' },
      thursday: { open: '07:00', close: '19:00' },
      friday: { open: '07:00', close: '19:00' },
      saturday: { open: '08:00', close: '16:00' },
      sunday: { open: '09:00', close: '15:00' },
    },
    services: ['Cardiologie', 'Dermatologie', 'Radiologie', 'Laboratoire'],
    isOpen: true,
  },
  {
    id: '4',
    name: 'Hôpital d\'Instruction des Armées',
    type: 'hospital',
    description: 'Hôpital public de référence avec service d\'urgences 24h/24.',
    address: '12 Route Nationale, Libreville',
    distance: 3.5,
    rating: 4.1,
    reviewCount: 203,
    tags: ['Public', 'Urgences', '24h/24'],
    hours: {
      monday: { open: '00:00', close: '23:59' },
      tuesday: { open: '00:00', close: '23:59' },
      wednesday: { open: '00:00', close: '23:59' },
      thursday: { open: '00:00', close: '23:59' },
      friday: { open: '00:00', close: '23:59' },
      saturday: { open: '00:00', close: '23:59' },
      sunday: { open: '00:00', close: '23:59' },
    },
    services: ['Urgences', 'Chirurgie', 'Maternité', 'Pédiatrie', 'Cardiologie'],
    isOpen: true,
  },
  {
    id: '5',
    name: 'Maman Christelle - Tradipraticienne',
    type: 'tradipractitioner',
    description: 'Spécialisée dans les soins traditionnels par les plantes médicinales.',
    address: '34 Quartier Akébé, Libreville',
    distance: 1.8,
    rating: 4.6,
    reviewCount: 67,
    tags: ['Plantes', 'Traditionnel', 'Naturel'],
    hours: {
      monday: { open: '08:00', close: '18:00' },
      tuesday: { open: '08:00', close: '18:00' },
      wednesday: { open: '08:00', close: '18:00' },
      thursday: { open: '08:00', close: '18:00' },
      friday: { open: '08:00', close: '18:00' },
      saturday: { open: '08:00', close: '15:00' },
      sunday: null,
    },
    services: ['Phytothérapie', 'Massage thérapeutique', 'Consultation traditionnelle'],
    isOpen: true,
  },
  {
    id: '6',
    name: 'Jean-Marie Express',
    type: 'delivery',
    description: 'Livreur rapide et fiable avec plus de 3 ans d\'expérience.',
    address: 'Zone: Libreville Centre',
    distance: 0.8,
    rating: 4.7,
    reviewCount: 92,
    tags: ['Rapide', 'AirtelMoney', 'MoovMoney'],
    hours: {
      monday: { open: '07:00', close: '21:00' },
      tuesday: { open: '07:00', close: '21:00' },
      wednesday: { open: '07:00', close: '21:00' },
      thursday: { open: '07:00', close: '21:00' },
      friday: { open: '07:00', close: '21:00' },
      saturday: { open: '08:00', close: '20:00' },
      sunday: { open: '09:00', close: '18:00' },
    },
    services: ['Livraison médicaments', 'Paiement mobile', 'Livraison express'],
    isOpen: true,
    deliveryFee: 2000,
    estimatedTime: '30-45 min',
  },
  {
    id: '7',
    name: 'Sophie Moto-Livraison',
    type: 'delivery',
    description: 'Livraison ultra-rapide en moto pour vos urgences médicales.',
    address: 'Zone: Libreville Nord',
    distance: 1.5,
    rating: 4.4,
    reviewCount: 78,
    tags: ['Moto', 'Urgence', 'MoovMoney'],
    hours: {
      monday: { open: '06:00', close: '22:00' },
      tuesday: { open: '06:00', close: '22:00' },
      wednesday: { open: '06:00', close: '22:00' },
      thursday: { open: '06:00', close: '22:00' },
      friday: { open: '06:00', close: '22:00' },
      saturday: { open: '07:00', close: '21:00' },
      sunday: { open: '08:00', close: '20:00' },
    },
    services: ['Livraison urgente', 'Paiement mobile', 'Disponible 7j/7'],
    isOpen: true,
    deliveryFee: 1500,
    estimatedTime: '15-25 min',
  },
  {
    id: '8',
    name: 'David Livraison Plus',
    type: 'delivery',
    description: 'Service de livraison économique avec large zone de couverture.',
    address: 'Zone: Grand Libreville',
    distance: 2.3,
    rating: 4.2,
    reviewCount: 156,
    tags: ['Économique', 'AirtelMoney', 'Zone étendue'],
    hours: {
      monday: { open: '08:00', close: '20:00' },
      tuesday: { open: '08:00', close: '20:00' },
      wednesday: { open: '08:00', close: '20:00' },
      thursday: { open: '08:00', close: '20:00' },
      friday: { open: '08:00', close: '20:00' },
      saturday: { open: '09:00', close: '19:00' },
      sunday: { open: '10:00', close: '17:00' },
    },
    services: ['Livraison standard', 'Paiement mobile', 'Zone étendue'],
    isOpen: true,
    deliveryFee: 1000,
    estimatedTime: '45-60 min',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: '1',
    title: 'Livraison acceptée',
    message: 'Jean-Marie Express a accepté votre demande de livraison. Il vous contactera sous peu.',
    type: 'delivery',
    fromProvider: 'Jean-Marie Express',
    providerId: '6',
    timestamp: '2024-03-15T10:30:00Z',
    isRead: false,
    priority: 'high',
    actionType: 'delivery_accepted',
  },
  {
    id: '2',
    title: 'Médicaments prêts',
    message: 'Vos médicaments sont prêts à la Pharmacie Centrale. Code: PH123A4',
    type: 'pharmacy',
    fromProvider: 'Pharmacie Centrale',
    providerId: '1',
    timestamp: '2024-03-15T09:15:00Z',
    isRead: false,
    priority: 'normal',
    actionType: 'prescription_ready',
  },
  {
    id: '3',
    title: 'Rappel rendez-vous',
    message: 'Votre rendez-vous avec Dr. Marie Moussavou est demain à 14h00.',
    type: 'doctor',
    fromProvider: 'Dr. Marie Moussavou',
    providerId: '2',
    timestamp: '2024-03-14T18:00:00Z',
    isRead: true,
    priority: 'normal',
    actionType: 'appointment_reminder',
  },
  {
    id: '4',
    title: 'Livreur en route',
    message: 'Sophie Moto-Livraison est en route. Arrivée estimée dans 15 minutes.',
    type: 'delivery',
    fromProvider: 'Sophie Moto-Livraison',
    providerId: '7',
    timestamp: '2024-03-15T11:45:00Z',
    isRead: false,
    priority: 'urgent',
    actionType: 'delivery_arriving',
  },
  {
    id: '5',
    title: 'Consultation confirmée',
    message: 'Votre consultation à la Clinique de la Sablière est confirmée pour le 16 mars à 10h00.',
    type: 'clinic',
    fromProvider: 'Clinique de la Sablière',
    providerId: '3',
    timestamp: '2024-03-14T16:20:00Z',
    isRead: true,
    priority: 'normal',
    actionType: 'booking_confirmed',
  },
];

export const getProvidersByType = (type: Provider['type']) =>
  mockProviders.filter((provider) => provider.type === type);

export const getProviderById = (id: string) =>
  mockProviders.find((provider) => provider.id === id);

export const getAllProviders = () => mockProviders;

export const mockMessages: Message[] = [
  {
    id: '1',
    fromProvider: 'Jean-Marie Express',
    providerId: '6',
    providerType: 'delivery',
    content: 'Bonjour ! Je suis en route pour récupérer vos médicaments à la pharmacie. J\'arrive dans 20 minutes.',
    timestamp: '2024-03-15T11:30:00Z',
    isRead: false,
    isFromUser: false,
  },
  {
    id: '2',
    fromProvider: 'Dr. Marie Moussavou',
    providerId: '2',
    providerType: 'doctor',
    content: 'Merci pour votre consultation. N\'oubliez pas de prendre vos médicaments 2 fois par jour.',
    timestamp: '2024-03-14T15:45:00Z',
    isRead: true,
    isFromUser: false,
  },
  {
    id: '3',
    fromProvider: 'Pharmacie Centrale',
    providerId: '1',
    providerType: 'pharmacy',
    content: 'Votre commande est prête ! Code de retrait : PH123A4. Nous fermons à 20h.',
    timestamp: '2024-03-15T09:00:00Z',
    isRead: false,
    isFromUser: false,
  },
];

export const mockUser: User = {
  id: '1',
  name: 'Marie Ndong',
  avatar: 'https://images.unsplash.com/photo-1494790108755-2616b332c738?w=100&h=100&fit=crop&crop=face&q=80',
  phone: '+241 XX XX XX XX',
  email: 'marie.ndong@example.com',
};

export const getNotifications = () => mockNotifications;

export const getMessages = () => mockMessages;

export const getCurrentUser = () => null; // Pas d'utilisateur connecté pour l'instant

export const getUnreadNotificationsCount = () =>
  mockNotifications.filter(notification => !notification.isRead).length;

export const getUnreadMessagesCount = () =>
  mockMessages.filter(message => !message.isRead).length;