import type { Provider } from '../types';

export const mockProviders: Provider[] = [
  {
    id: '1',
    name: 'Pharmacie Centrale',
    type: 'pharmacy',
    description: 'Pharmacie moderne avec large gamme de médicaments et conseils personnalisés.',
    address: '123 Avenue de l\'Indépendance, Libreville',
    distance: 0.5,
    rating: 4.5,
    reviewCount: 124,
    tags: ['24h/24', 'Livraison', 'Conseil'],
    hours: {
      monday: { open: '08:00', close: '20:00' },
      tuesday: { open: '08:00', close: '20:00' },
      wednesday: { open: '08:00', close: '20:00' },
      thursday: { open: '08:00', close: '20:00' },
      friday: { open: '08:00', close: '20:00' },
      saturday: { open: '09:00', close: '18:00' },
      sunday: { open: '10:00', close: '16:00' },
    },
    services: ['Médicaments', 'Parapharmacie', 'Conseil pharmaceutique', 'Livraison'],
    isOpen: true,
  },
  {
    id: '2',
    name: 'Dr. Marie Moussavou',
    type: 'doctor',
    description: 'Médecin généraliste avec plus de 15 ans d\'expérience.',
    address: '45 Rue de la Paix, Libreville',
    distance: 1.2,
    rating: 4.8,
    reviewCount: 89,
    tags: ['Généraliste', 'Urgences', 'Consultation'],
    hours: {
      monday: { open: '09:00', close: '17:00' },
      tuesday: { open: '09:00', close: '17:00' },
      wednesday: { open: '09:00', close: '17:00' },
      thursday: { open: '09:00', close: '17:00' },
      friday: { open: '09:00', close: '17:00' },
      saturday: { open: '09:00', close: '12:00' },
      sunday: null,
    },
    services: ['Consultation générale', 'Vaccination', 'Certificats médicaux'],
    isOpen: true,
  },
  {
    id: '3',
    name: 'Clinique de la Sablière',
    type: 'clinic',
    description: 'Clinique moderne avec équipements de pointe et équipe médicale qualifiée.',
    address: '78 Boulevard Triomphal, Libreville',
    distance: 2.1,
    rating: 4.3,
    reviewCount: 156,
    tags: ['Spécialisée', 'Équipements', 'Urgences'],
    hours: {
      monday: { open: '07:00', close: '19:00' },
      tuesday: { open: '07:00', close: '19:00' },
      wednesday: { open: '07:00', close: '19:00' },
      thursday: { open: '07:00', close: '19:00' },
      friday: { open: '07:00', close: '19:00' },
      saturday: { open: '08:00', close: '16:00' },
      sunday: { open: '09:00', close: '15:00' },
    },
    services: ['Cardiologie', 'Dermatologie', 'Radiologie', 'Laboratoire'],
    isOpen: true,
  },
  {
    id: '4',
    name: 'Hôpital d\'Instruction des Armées',
    type: 'hospital',
    description: 'Hôpital public de référence avec service d\'urgences 24h/24.',
    address: '12 Route Nationale, Libreville',
    distance: 3.5,
    rating: 4.1,
    reviewCount: 203,
    tags: ['Public', 'Urgences', '24h/24'],
    hours: {
      monday: { open: '00:00', close: '23:59' },
      tuesday: { open: '00:00', close: '23:59' },
      wednesday: { open: '00:00', close: '23:59' },
      thursday: { open: '00:00', close: '23:59' },
      friday: { open: '00:00', close: '23:59' },
      saturday: { open: '00:00', close: '23:59' },
      sunday: { open: '00:00', close: '23:59' },
    },
    services: ['Urgences', 'Chirurgie', 'Maternité', 'Pédiatrie', 'Cardiologie'],
    isOpen: true,
  },
  {
    id: '5',
    name: 'Maman Christelle - Tradipraticienne',
    type: 'tradipractitioner',
    description: 'Spécialisée dans les soins traditionnels par les plantes médicinales.',
    address: '34 Quartier Akébé, Libreville',
    distance: 1.8,
    rating: 4.6,
    reviewCount: 67,
    tags: ['Plantes', 'Traditionnel', 'Naturel'],
    hours: {
      monday: { open: '08:00', close: '18:00' },
      tuesday: { open: '08:00', close: '18:00' },
      wednesday: { open: '08:00', close: '18:00' },
      thursday: { open: '08:00', close: '18:00' },
      friday: { open: '08:00', close: '18:00' },
      saturday: { open: '08:00', close: '15:00' },
      sunday: null,
    },
    services: ['Phytothérapie', 'Massage thérapeutique', 'Consultation traditionnelle'],
    isOpen: true,
  },
];

export const getProvidersByType = (type: Provider['type']) =>
  mockProviders.filter((provider) => provider.type === type);

export const getProviderById = (id: string) =>
  mockProviders.find((provider) => provider.id === id);

export const getAllProviders = () => mockProviders;